export { default as Login } from './Login/Login'
export { default as Register } from './Register/Register'
export { default as Profile } from './Profile/Profile'
export { default as ForgotPassword } from './ForgotPassword/ForgotPassword'
export { default as UpdateProfile } from './UpdateProfile/UpdateProfile'
